steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', './backend']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

# Substitutions for dynamic values
substitutions:
  _SERVICE_NAME: 'business-chemsitry-backend'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'